sudo: required

language: ruby

rvm:
  - 2.2.3

git:
  depth: 25

services:
  - docker

before_install:
  - docker build -t rmarchei/icinga2 .
  - docker run -d --name icinga2 rmarchei/icinga2
  - docker ps -a
  - docker exec -it icinga2 cat /etc/centos-release

script:
  - docker exec -it icinga2 /usr/sbin/icinga2 --version

after_script:
  - docker images
